auto: true
safe: true
server: true
markdown: kramdown
pygments: true
permalink: /:title.html

default_theme: bright
default_body_class: list

author:
    name: Varya Stepanova
    url:  http://varya.me
    company:
        name: Zalando SE
        url:  https://tech.zalando.com/

fork_url: https://github.com/varya/component-development-css-2016
progress: true
